var archiveBrand='',archiveSection='';
var docs=[
{brand:'Daikin',type:'manuali',family:'Sky Air',model:'FCAG35~140BVEB',year:'2025',title:'Guida installatore e utente FCAG-B',description:'Installazione, uso, diagnostica e panoramica dei codici di malfunzionamento.',url:'https://www.daikin.eu/content/dam/document-library/Installer-reference-guide/ac/sky-air/fcag-b/FCAG-B_Installer.User%20reference%20guide_4PIT561448-1C_Italian.pdf'},
{brand:'Daikin',type:'service',family:'e-Care / e-Doctor',model:'Portale professionale',year:'attuale',title:'Daikin e-Care',description:'App e canale ufficiale per tecnici. Le funzioni riservate richiedono un account autorizzato.',url:'https://www.daikin.it/it_it/privati/services/apps-and-connectivity.html'},
{brand:'Unical',type:'archivio',family:'Fuori listino',model:'!DEA',year:'storico',title:'!DEA — documentazione di archivio',description:'Manuali utente, manuali installazione e dati tecnici del prodotto fuori listino.',url:'https://www.unicalag.it/fuori-listino/75/dea'},
{brand:'Unical',type:'service',family:'uFly',model:'Controllo e termoregolazione',year:'attuale',title:'App Unical uFly',description:'Controllo impianto, storico errori, notifiche e reset per sistemi compatibili.',url:'https://www.unicalag.it/news/prodotti/1863/app-unical-ufly'},
{brand:'Wolf',type:'manuali',family:'Riscaldamento',model:'Caldaie, PDC e ventilazione',year:'attuale e storico',title:'Download tecnici WOLF',description:'Documentazione tecnica, manuali di installazione e professional manual.',url:'https://www.wolf.eu/it-it/professionisti/downloads/riscaldamento'},
{brand:'Wolf',type:'schemi',family:'Strumenti professionali',model:'Schemi idraulici',year:'attuale',title:'Strumenti e schemi WOLF',description:'Database e strumenti digitali ufficiali del costruttore.',url:'https://www.wolf.eu/it-it/professionisti/tools'},
{brand:'Wolf',type:'service',family:'WOLF PRO',model:'WOLF Service App',year:'attuale',title:'WOLF Service App',description:'Canale WOLF PRO per rete assistenza, strumenti professionali e gestione impianti.',url:'https://www.wolf.eu/it-it/professionisti/rete-assistenza-wolf-pro'}];
var codes=[
{code:'A0',title:'Protezione esterna attivata'},{code:'A1',title:'Malfunzionamento PCB unità interna'},{code:'A5',title:'Controllo alta pressione in riscaldamento / protezione antigelo in raffreddamento'},{code:'A6',title:'Malfunzionamento motore ventilatore'}].map(x=>({...x,brand:'Daikin',family:'Sky Air FCAG-B',model:'FCAG35~140BVEB',year:'2025',url:docs[0].url}));
var labels={manuali:'Manuali',errori:'Codici errore',ricambi:'Ricambi',schemi:'Schemi',service:'Service / Parametri',dati:'Dati tecnici',cerca:'Cerca modello',archivio:'Archivio storico'};
function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function handleLogin(e){e.preventDefault();document.getElementById('view-login').classList.add('hidden');document.getElementById('view-home').classList.remove('hidden')}
function logout(){document.getElementById('view-home').classList.add('hidden');document.getElementById('view-login').classList.remove('hidden')}
function selectBrand(b){archiveBrand=b;document.getElementById('brand-title').innerText=b.toUpperCase();document.getElementById('view-home').classList.add('hidden');document.getElementById('view-functions').classList.remove('hidden')}
function goToHome(){document.getElementById('view-functions').classList.add('hidden');document.getElementById('view-home').classList.remove('hidden')}
function openBrandMenu(){document.getElementById('view-content').classList.add('hidden');document.getElementById('view-functions').classList.remove('hidden')}
function card(x){return '<article class="bg-slate-800 p-5 rounded-xl border border-slate-700"><div class="flex flex-wrap gap-2 text-[10px] uppercase font-bold tracking-wide"><span class="bg-blue-500/15 text-blue-300 px-2 py-1 rounded">'+esc(x.type)+'</span><span class="bg-slate-700 text-slate-300 px-2 py-1 rounded">'+esc(x.year)+'</span></div><h3 class="font-bold text-slate-100 mt-3">'+esc(x.title)+'</h3><p class="text-xs text-slate-400 mt-1">'+esc(x.family)+' · '+esc(x.model)+'</p><p class="text-sm text-slate-300 mt-3">'+esc(x.description)+'</p><a href="'+esc(x.url)+'" target="_blank" rel="noopener noreferrer" class="inline-block mt-4 text-xs bg-blue-600 hover:bg-blue-500 text-white px-3 py-2 rounded"><i class="fa-solid fa-arrow-up-right-from-square mr-1"></i> Apri fonte ufficiale</a></article>'}
function render(q=''){let type=archiveSection==='cerca'?'':archiveSection,n=q.toLowerCase(),list=docs.filter(x=>x.brand===archiveBrand&&(!type||x.type===type||(type==='dati'&&x.type==='manuali'))&&Object.values(x).join(' ').toLowerCase().includes(n));document.getElementById('results').innerHTML=list.length?list.map(card).join(''):'<div class="bg-slate-800 p-6 rounded-xl border border-slate-700 text-center text-sm text-slate-400">Nessuna voce trovata.</div>'}
function renderCodes(q=''){let n=q.toLowerCase(),list=codes.filter(x=>Object.values(x).join(' ').toLowerCase().includes(n));document.getElementById('results').innerHTML=list.length?list.map(x=>'<article class="bg-slate-800 p-5 rounded-xl border border-slate-700"><div class="flex justify-between gap-3"><span class="bg-red-500/20 text-red-300 text-xs font-bold px-2.5 py-1 rounded">'+x.code+'</span><span class="text-xs text-slate-400">'+x.family+' · '+x.year+'</span></div><h3 class="font-bold text-slate-100 mt-3">'+x.title+'</h3><p class="text-xs text-slate-400 mt-1">Modello di riferimento: '+x.model+'. Verifica sempre il manuale specifico della macchina.</p><a href="'+x.url+'" target="_blank" rel="noopener noreferrer" class="inline-block mt-4 text-xs bg-blue-600 hover:bg-blue-500 text-white px-3 py-2 rounded">Apri manuale ufficiale</a></article>').join(''):'<div class="bg-slate-800 p-6 rounded-xl border border-slate-700 text-center text-sm text-slate-400">Nessun codice catalogato per questa ricerca.</div>'}
function openSection(s){archiveSection=s;document.getElementById('view-functions').classList.add('hidden');document.getElementById('view-content').classList.remove('hidden');document.getElementById('section-title').innerText=archiveBrand+' — '+labels[s];document.getElementById('section-subtitle').innerText=s==='errori'?'Ricerca verificata per serie e modello':'Fonti ufficiali del costruttore';if(s==='ricambi'){document.getElementById('section-body').innerHTML='<div class="bg-slate-800 p-8 rounded-xl border border-slate-700 text-center"><i class="fa-solid fa-gears text-4xl text-emerald-400 mb-3"></i><h3 class="font-bold text-slate-200">Ricambi ed esplosi</h3><p class="text-sm text-slate-400 mt-2">Saranno inseriti solo cataloghi ed esplosi forniti o pubblicati ufficialmente dal costruttore.</p></div>';return}document.getElementById('section-body').innerHTML='<div class="bg-slate-800 p-4 rounded-xl border border-slate-700"><label class="block text-xs uppercase text-slate-400 mb-2">'+(s==='errori'?'Cerca codice, serie o modello':'Cerca modello, serie, anno o documento')+'</label><input id="search" type="search" placeholder="Es. FCAG, Altherma, !DEA, CGB-2..." class="w-full bg-slate-900 border border-slate-700 rounded-lg p-3 text-sm text-slate-100 focus:outline-none focus:border-blue-500"><p class="text-xs text-slate-500 mt-2">Le fonti si aprono sul sito ufficiale del produttore.</p></div><div id="results" class="space-y-3"></div>';document.getElementById('search').addEventListener('input',e=>s==='errori'?renderCodes(e.target.value):render(e.target.value));s==='errori'?renderCodes():render()}
