var tpCode='';
var tpCatalog={
  Daikin:[
    {title:'Condizionatori residenziali',icon:'fa-snowflake',models:[
      {code:'FTXA20/25/35/42/50 A2V1B',name:'Stylish',year:'attuale',docs:[['Manuale installazione','https://www.daikin.eu/content/dam/document-library/installation-manuals/ac/split/CTXA-AW_AS_BS_AT_BT_BB_FTXA-AW_AS_BS_AT_BT_BB_Installation%20manual_3PIT697375-1_Italian.pdf'],['Guida installatore','https://www.daikin.eu/content/dam/document-library/Installer-reference-guide/ac/split/CTXA-AW_AS_BS_AT_BT_BB_FTXA-AW_AS_BS_AT_BT_BB_Installer%20reference%20guide_4PIT518023-3K_Italian.pdf'],['Manuale operativo','https://www.daikin.eu/content/dam/document-library/operation-manuals/ac/split/CTXA-AWAS,BS,AT,BT,BB,FTXA-AWAS,BS,AT,BT,BB_3PIT485919-7S_Operation%20manual_Italian.pdf']]},
      {code:'2AMXM-M',name:'Multi Split 2M',year:'attuale',page:'https://www.daikin.eu/en_us/products/product.html/2AMXM-M.html'},
      {code:'4MWXM-A',name:'Multi Split 4M',year:'attuale',page:'https://www.daikin.eu/en_us/products/product.html/4MWXM-A.html'}
      ,{code:'FTXJ-AW / RXJ-A',name:'Emura',year:'attuale',docs:[['Manuale installazione Emura','https://www.daikin.eu/content/dam/document-library/installation-manuals/ac/split/ftxj-ab9/FTXJ-AB9.FTXJ-AW9.FTXJ-AS9_Installation%20manual_3PIT664524-5J_Italian.pdf']]},{code:'FTXM-R · CTXM-R · ATXM-R / RXM-R',name:'Perfera',year:'archivio',docs:[['Manuale installazione Perfera','https://www.daikin.eu/content/dam/document-library/installation-manuals/ac/split/ctxm-r/CTXM-R_FTXM-R_ATXM-R_Installation%20manual_3PIT697375-2_Italian.pdf'],['Guida installatore Perfera','https://www.daikin.eu/content/dam/document-library/Installer-reference-guide/ac/split/ctxm-r/CTXM-R_FTXM-R_ATXM-R_Installer%20reference%20guide_4PIT518023-8K_Italian.pdf']]},{code:'FTXTM-R / RXTM-R',name:'Perfera All Seasons',year:'archivio',docs:[['Manuale installazione Perfera All Seasons','https://www.daikin.eu/content/dam/document-library/installation-manuals/ac/split/ftxtm-r/FTXTM-R_Installation%20manual_3PIT482320-13U_Italian.pdf']]},{code:'FTXP / RXP',name:'Comfora',year:'attuale'},{code:'FTXF / RXF',name:'Sensira',year:'attuale'}
    ]},
    {title:'Multisplit',icon:'fa-code-branch',models:[{code:'FTXJ · FTXA · FTXM · FTXP / 2MXM · 3MXM · 4MXM · 5MXM',name:'Multisplit',year:'attuale'},{code:'Unità residenziali / 4MWXM · 5MWXM',name:'Multisplit Multi+',year:'attuale'},{code:'Sensira compatibili / 2MXF · 3MXF',name:'Multisplit Sensira',year:'attuale'}]},
    {title:'Sky Air commerciale',icon:'fa-building',models:[
      {code:'FCAG35~140BVEB',name:'Cassetta Sky Air FCAG-B',year:'2025',docs:[['Guida installatore e utente','https://www.daikin.eu/content/dam/document-library/Installer-reference-guide/ac/sky-air/fcag-b/FCAG-B_Installer.User%20reference%20guide_4PIT561448-1C_Italian.pdf']]},
      {code:'FCAG-B / RZAG-A',name:'Sky Air Alpha',year:'attuale',page:'https://www.daikin.eu/en_us/products/product.html/FCAG-B---RZAG-A.html'}
      ,{code:'FAA-A / RZAG-A',name:'Sky Air parete',year:'attuale'},{code:'FBA-A · FBA-A9 / RZAG-A',name:'Sky Air canalizzato',year:'attuale'}
    ]},
    {title:'Pompe di calore Altherma',icon:'fa-temperature-arrow-up',models:[
      {code:'EHBX · EHFZ / ERGA · ERLA',name:'Daikin Altherma 3 R',year:'attuale'},
      {code:'E-CARE',name:'e-Care / e-Doctor',year:'attuale',page:'https://www.daikin.it/it_it/privati/services/apps-and-connectivity.html'}
      ,{code:'EHVH · EKHBRD / ERLQ',name:'Altherma Split',year:'archivio e attuale'},{code:'— / EDHQ-BB6W1',name:'Altherma Monobloc',year:'archivio'},{code:'EHSX-D / unità esterna abbinata',name:'Altherma ECH2O',year:'archivio e attuale'},{code:'EHYKOMB-AA / EVLQ abbinata',name:'Altherma ibrida',year:'archivio e attuale'}
    ]},
    {title:'VRV / VRF',icon:'fa-industry',models:[
      {code:'RXYSCQ-TV1',name:'VRV-S',year:'attuale',page:'https://www.daikin.eu/en_us/products/product.html/RXYSCQ-TV1.html'},
      {code:'RXYQ-UD',name:'VRV IV+',year:'archivio',page:'https://www.daikin.eu/en_us/products/product.html/RXYQ-UD.html'},
      {code:'RYMQ-U',name:'VRV IV',year:'archivio',page:'https://www.daikin.eu/en_us/products/product.html/RYMQ-U.html'}
      ,{code:'FX interne / RXYSQ-TV1',name:'VRV IV S',year:'archivio'},{code:'FX interne / RXYQQ8–20T7Y1B',name:'VRV IV',year:'archivio'}
    ]},
    {title:'Ventilazione e unità interne',icon:'fa-wind',models:[
      {code:'FXHA-A',name:'Unità interna canalizzabile VRV',year:'attuale',page:'https://www.daikin.eu/en_us/products/product.html/FXHA-A.html'},
      {code:'D9HA2-A',name:'Ventilazione residenziale',year:'attuale',page:'https://www.daikin.eu/en_us/products/product.html/D9HA2-A.html'}
    ]}
  ],
  Unical:[{title:'App e archivio Unical',icon:'fa-mobile-screen',models:[{code:'UFLY',name:'App Unical uFly',year:'attuale',page:'https://www.unicalag.it/news/prodotti/1863/app-unical-ufly'},{code:'!DEA',name:'Caldaie fuori listino',year:'storico',page:'https://www.unicalag.it/fuori-listino/75/dea'}]}],
  Wolf:[{title:'Service WOLF',icon:'fa-screwdriver-wrench',models:[{code:'WOLF-PRO',name:'WOLF Service App',year:'attuale',page:'https://www.wolf.eu/it-it/professionisti/rete-assistenza-wolf-pro'},{code:'WOLF-DOWNLOAD',name:'Download riscaldamento',year:'attuale e storico',page:'https://www.wolf.eu/it-it/professionisti/downloads/riscaldamento'},{code:'WOLF-SCHEMI',name:'Schemi idraulici e tool',year:'attuale',page:'https://www.wolf.eu/it-it/professionisti/tools'}]}]
};function tpHeader(title,sub,back){var logo=archiveBrand==='Daikin'?'<img src="Screenshot%202026-09-25%20alle%2009.38.35.png" alt="Daikin" class="h-10 w-auto rounded-md bg-white p-1 shadow-lg">':'';return '<header class="flex items-center space-x-3 mb-8 border-b border-slate-800 pb-4"><button onclick="'+back+'" class="bg-slate-800 p-2 rounded-lg border border-slate-700"><i class="fa-solid fa-arrow-left"></i></button><div class="flex items-center gap-3">'+logo+'<div><h2 class="text-xl font-bold">'+title+'</h2><p class="text-sm text-slate-400">'+sub+'</p></div></div></header>';}
function tpShowCategories(){var a=tpCatalog[archiveBrand]||[],v=document.getElementById('view-functions');v.innerHTML=tpHeader(archiveBrand+' — Catalogo modelli','Scegli una categoria per visualizzare i codici','goToHome()')+'<div class="grid grid-cols-1 md:grid-cols-2 gap-4">'+a.map(function(g,i){return '<button onclick="tpShowModels('+i+')" class="bg-slate-800 hover:bg-slate-700 border border-slate-700 hover:border-blue-500 p-5 rounded-xl text-left"><i class="fa-solid '+g.icon+' text-blue-400 text-xl"></i><h3 class="font-bold mt-3">'+g.title+'</h3><p class="text-sm text-slate-400 mt-1">'+g.models.length+' modelli o serie</p><span class="inline-block text-xs text-blue-300 mt-4">Apri codici →</span></button>';}).join('')+'</div>';}
function tpShowModels(group){var g=tpCatalog[archiveBrand][group],v=document.getElementById('view-functions');v.innerHTML=tpHeader(archiveBrand+' — '+g.title,'Scegli il codice esatto del prodotto','tpShowCategories()')+'<div class="grid grid-cols-1 md:grid-cols-2 gap-4">'+g.models.map(function(m,i){return '<button onclick="tpShowDetail('+group+','+i+')" class="bg-slate-800 hover:bg-slate-700 border border-slate-700 hover:border-blue-500 p-5 rounded-xl text-left"><div class="flex justify-between gap-3"><b class="font-mono text-blue-300">'+m.code+'</b><span class="text-xs text-slate-500 whitespace-nowrap">'+m.year+'</span></div><h3 class="font-bold mt-3">'+m.name+'</h3><span class="inline-block text-xs text-blue-300 mt-4">Documenti e archivio →</span></button>';}).join('')+'</div>';}
function tpShowDetail(group,item){var m=tpCatalog[archiveBrand][group].models[item],v=document.getElementById('view-functions'),docs=(m.docs||[]).map(function(d){return '<a href="'+d[1]+'" target="_blank" rel="noopener" class="block bg-blue-600 hover:bg-blue-500 p-4 rounded-xl font-bold"><i class="fa-solid fa-file-pdf mr-2"></i>'+d[0]+' <span class="float-right">↗</span></a>';}).join('');if(m.page){docs+='<a href="'+m.page+'" target="_blank" rel="noopener" class="block bg-slate-700 hover:bg-slate-600 border border-slate-600 p-4 rounded-xl font-bold"><i class="fa-solid fa-arrow-up-right-from-square mr-2"></i>Scheda e documentazione ufficiale <span class="float-right">↗</span></a>';}var sections=[['manuali','fa-book','Manuali'],['errori','fa-triangle-exclamation','Codici errore'],['ricambi','fa-gear','Ricambi'],['schemi','fa-pen-ruler','Schemi'],['service','fa-sliders','Service'],['dati','fa-circle-info','Dati tecnici'],['archivio','fa-box-archive','Archivio storico']];v.innerHTML=tpHeader(archiveBrand+' — '+m.code,m.name+' · '+m.year,'tpShowModels('+group+')')+'<div class="space-y-3 mb-8">'+docs+'<p class="text-xs text-slate-500 pt-1">I link aprono fonti ufficiali del produttore in una nuova scheda.</p></div><h3 class="font-bold mb-3">Archivio tecnico</h3><div class="grid grid-cols-2 md:grid-cols-3 gap-3">'+sections.map(function(s){return '<button onclick="tpCode=\''+m.code+'\';openSection(\''+s[0]+'\')" class="bg-slate-800 hover:bg-slate-700 border border-slate-700 p-4 rounded-xl text-left"><i class="fa-solid '+s[1]+' text-blue-400"></i><div class="font-bold text-sm mt-2">'+s[2]+'</div></button>';}).join('')+'</div>';}
function tpChoose(code){tpCode=code;var groups=tpCatalog[archiveBrand]||[];for(var i=0;i<groups.length;i++){for(var j=0;j<groups[i].models.length;j++){if(groups[i].models[j].code===code){tpShowDetail(i,j);return;}}}tpShowCategories();}
function tpModels(){tpShowCategories();}
function openBrandMenu(){document.getElementById('view-content').classList.add('hidden');document.getElementById('view-functions').classList.remove('hidden');tpShowCategories();}
setTimeout(function(){selectBrand=function(b){archiveBrand=b;tpCode='';document.getElementById('view-home').classList.add('hidden');document.getElementById('view-functions').classList.remove('hidden');tpShowCategories();};},0);
