/* Archivio tecnico Daikin: collegamenti esclusivamente a fonti ufficiali. */
(function(){
var support='https://www.daikin.it/it_it/privati/services/cataloghi-e-documentazione.html';
var parts='https://www.daikin.eu/en_us/support-and-manuals.html';
var logo='Screenshot%202026-09-25%20alle%2009.38.35.png', selected;
function M(name,code,year,type,docs){return {name:name,code:code,year:year,type:type,docs:docs||[['Documentazione ufficiale',support]]};}
var groups=[
 {title:'Condizionatori residenziali',icon:'fa-snowflake',models:[
  M('Stylish','FTXA20/25/35/42/50 A2V1B','attuale','Split a parete',[['Manuale installazione','https://www.daikin.eu/content/dam/document-library/installation-manuals/ac/split/CTXA-AW_AS_BS_AT_BT_BB_FTXA-AW_AS_BS_AT_BT_BB_Installation%20manual_3PIT697375-1_Italian.pdf'],['Guida installatore','https://www.daikin.eu/content/dam/document-library/Installer-reference-guide/ac/split/CTXA-AW_AS_BS_AT_BT_BB_FTXA-AW_AS_BS_AT_BT_BB_Installer%20reference%20guide_4PIT518023-3K_Italian.pdf'],['Manuale operativo','https://www.daikin.eu/content/dam/document-library/operation-manuals/ac/split/CTXA-AWAS,BS,AT,BT,BB,FTXA-AWAS,BS,AT,BT,BB_3PIT485919-7S_Operation%20manual_Italian.pdf']]),
  M('Emura','FTXJ-AW / RXJ-A','attuale','Split a parete',[['Manuale installazione','https://www.daikin.eu/content/dam/document-library/installation-manuals/ac/split/ftxj-ab9/FTXJ-AB9.FTXJ-AW9.FTXJ-AS9_Installation%20manual_3PIT664524-5J_Italian.pdf']]),
  M('Perfera','FTXM-R · CTXM-R · ATXM-R / RXM-R','archivio','Split a parete',[['Manuale installazione','https://www.daikin.eu/content/dam/document-library/installation-manuals/ac/split/ctxm-r/CTXM-R_FTXM-R_ATXM-R_Installation%20manual_3PIT697375-2_Italian.pdf'],['Guida installatore','https://www.daikin.eu/content/dam/document-library/Installer-reference-guide/ac/split/ctxm-r/CTXM-R_FTXM-R_ATXM-R_Installer%20reference%20guide_4PIT518023-8K_Italian.pdf']]),
  M('Perfera All Seasons','FTXTM-R / RXTM-R','archivio','Split a parete',[['Manuale installazione','https://www.daikin.eu/content/dam/document-library/installation-manuals/ac/split/ftxtm-r/FTXTM-R_Installation%20manual_3PIT482320-13U_Italian.pdf']]),
  M('Comfora','FTXP / RXP','attuale','Split a parete'),M('Sensira','FTXF / RXF','attuale','Split a parete')]},
 {title:'Multisplit',icon:'fa-code-branch',models:[M('Multisplit','FTXJ · FTXA · FTXM · FTXP / 2MXM · 3MXM · 4MXM · 5MXM','attuale','Sistema multi'),M('Multisplit Multi+','Unità residenziali / 4MWXM · 5MWXM','attuale','Sistema multi'),M('Multisplit Sensira','Sensira compatibili / 2MXF · 3MXF','attuale','Sistema multi')]},
 {title:'Sky Air commerciale',icon:'fa-building',models:[M('Cassetta Sky Air FCAG-B','FCAG35~140BVEB','2025','Cassetta a 4 vie',[['Guida installatore e utente','https://www.daikin.eu/content/dam/document-library/Installer-reference-guide/ac/sky-air/fcag-b/FCAG-B_Installer.User%20reference%20guide_4PIT561448-1C_Italian.pdf']]),M('Sky Air parete','FAA-A / RZAG-A','attuale','Unità a parete'),M('Sky Air canalizzato','FBA-A · FBA-A9 / RZAG-A','attuale','Unità canalizzata')]},
 {title:'Pompe di calore Altherma',icon:'fa-temperature-arrow-up',models:[M('Altherma 3 R','EHBX · EHFZ / ERGA · ERLA','attuale','Pompa di calore aria-acqua'),M('Altherma Split','EHVH · EKHBRD / ERLQ','archivio e attuale','Pompa di calore split'),M('Altherma Monobloc','EDHQ-BB6W1','archivio','Pompa di calore monobloc'),M('Altherma ECH2O','EHSX-D / unità esterna abbinata','archivio e attuale','Accumulo e PDC'),M('Altherma ibrida','EHYKOMB-AA / EVLQ abbinata','archivio e attuale','Sistema ibrido')]},
 {title:'VRV / VRF',icon:'fa-industry',models:[M('VRV IV S','FX interne / RXYSQ-TV1','archivio','VRV compatto'),M('VRV IV','FX interne / RXYQQ8–20T7Y1B','archivio','VRV')]}];
function esc(x){return String(x).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function head(t,s,b){return '<header class="flex items-center gap-3 mb-7 border-b border-slate-800 pb-4"><button onclick="'+b+'" class="bg-slate-800 p-2 rounded-lg border border-slate-700"><i class="fa-solid fa-arrow-left"></i></button><img src="'+logo+'" alt="Daikin" class="h-9 w-auto rounded bg-white p-1"><div><h2 class="text-xl font-bold">'+esc(t)+'</h2><p class="text-xs text-slate-400">'+esc(s)+'</p></div></header>'}
function categories(){var v=document.getElementById('view-functions');v.innerHTML=head('Daikin — Catalogo tecnico','Scegli famiglia e modello','goToHome()')+'<div class="grid grid-cols-1 md:grid-cols-2 gap-4">'+groups.map(function(g,i){return '<button onclick="daikinModels('+i+')" class="bg-slate-800 hover:bg-slate-700 border border-slate-700 hover:border-blue-500 p-5 rounded-xl text-left"><i class="fa-solid '+g.icon+' text-blue-400 text-xl"></i><h3 class="font-bold mt-3">'+g.title+'</h3><p class="text-sm text-slate-400 mt-1">'+g.models.length+' serie disponibili</p><span class="inline-block text-xs text-blue-300 mt-4">Apri modelli →</span></button>'}).join('')+'</div>'}
function models(i){var g=groups[i],v=document.getElementById('view-functions');v.innerHTML=head('Daikin — '+g.title,'Scegli il modello installato','daikinCategories()')+'<div class="grid grid-cols-1 md:grid-cols-2 gap-4">'+g.models.map(function(m,j){return '<button onclick="daikinDetail('+i+','+j+')" class="bg-slate-800 hover:bg-slate-700 border border-slate-700 hover:border-blue-500 p-5 rounded-xl text-left"><div class="flex justify-between gap-3"><b class="font-mono text-blue-300 text-sm">'+esc(m.code)+'</b><span class="text-xs text-slate-500">'+esc(m.year)+'</span></div><h3 class="font-bold mt-3">'+esc(m.name)+'</h3><p class="text-xs text-slate-400 mt-1">'+esc(m.type)+'</p><span class="inline-block text-xs text-blue-300 mt-4">Apri scheda tecnica →</span></button>'}).join('')+'</div>'}
function detail(i,j){selected=groups[i].models[j];var m=selected,v=document.getElementById('view-functions'),d=m.docs.map(function(x){return '<a href="'+esc(x[1])+'" target="_blank" rel="noopener noreferrer" class="block bg-blue-600 hover:bg-blue-500 p-4 rounded-xl font-semibold"><i class="fa-solid fa-file-pdf mr-2"></i>'+esc(x[0])+' <span class="float-right">↗</span></a>'}).join(''),a=[['manuali','fa-book','Manuali'],['errori','fa-triangle-exclamation','Codici errore'],['ricambi','fa-gears','Ricambi'],['schemi','fa-diagram-project','Schemi'],['service','fa-sliders','Parametri'],['dati','fa-circle-info','Dati tecnici']];v.innerHTML=head('Daikin — '+m.name,m.code+' · '+m.year,'daikinModels('+i+')')+'<div class="space-y-3 mb-7">'+d+'<a href="'+support+'" target="_blank" rel="noopener noreferrer" class="block bg-slate-700 p-4 rounded-xl text-sm">Catalogo e documentazione ufficiale Daikin <span class="float-right">↗</span></a></div><h3 class="font-bold mb-3">Scheda service del modello</h3><div class="grid grid-cols-2 md:grid-cols-3 gap-3">'+a.map(function(x){return '<button onclick="daikinSection(\''+x[0]+'\')" class="bg-slate-800 hover:bg-slate-700 border border-slate-700 p-4 rounded-xl text-left"><i class="fa-solid '+x[1]+' text-blue-400"></i><div class="font-bold text-sm mt-2">'+x[2]+'</div></button>'}).join('')+'</div>'}
var codes=[['A0','Protezione esterna intervenuta','Togli alimentazione e verifica il guasto dell’unità esterna associata prima del ripristino.'],['A1','Scheda elettronica (EEPROM) interna','Togli alimentazione; controlla connettori e alimentazione della scheda. Se persiste, serve diagnosi tecnica.'],['A3','Scarico condensa / pompa condensa','Verifica galleggiante, tubo, pendenza, pompa e connettori; elimina le ostruzioni.'],['A6','Motore ventilatore interno','Controlla girante libera, connettori e scheda; non avviare con protezioni rimosse.'],['C4 / C5 / C9 / CA','Sonde interne','Controlla cablaggio e confronta il valore della sonda con la tabella del manuale di serie.'],['U0','Refrigerante insufficiente','Non rabboccare senza ricerca perdite: recupero, prova tenuta, vuoto e carica a peso solo da personale F-Gas.'],['U2','Anomalia alimentazione','Controlla tensione, morsetti e protezioni secondo la procedura del manuale.'],['U4','Comunicazione interno–esterno','Controlla collegamento morsetti 1-2-3, continuità e alimentazione di entrambe le unità.'],['UA','Configurazione errata','Verifica compatibilità e configurazione della combinazione interno–esterno.'],['E1','Scheda elettronica esterna','Togli alimentazione e verifica cablaggi, connettori e alimentazione della scheda.'],['E3','Alta pressione','Verifica flusso aria/acqua, valvole e scambiatore. Non bypassare le protezioni.'],['E4','Bassa pressione','Verifica condizioni di esercizio e circuito frigorifero; ricerca perdite solo da tecnico F-Gas.'],['E5 / E6','Avviamento compressore','Verifica alimentazione e diagnostica inverter; non forzare riavvii ripetuti.'],['E7 / H7 / P7','Ventilatore esterno','Verifica ostacoli, connettori, tensione e comando scheda.'],['F3','Mandata compressore elevata','Verifica scambio termico, carica e sensore scarico; arresta se il codice ritorna.'],['L1 / L4 / L5 / P4','Inverter','Intervento riservato a personale elettrico qualificato: attendere scarica condensatori e seguire manuale service.']];
function box(t,text,icon,label,url){return '<div class="bg-slate-800 border border-slate-700 p-6 rounded-xl"><i class="fa-solid '+icon+' text-blue-400 text-3xl"></i><h3 class="font-bold text-lg mt-3">'+t+'</h3><p class="text-sm text-slate-400 mt-2">'+text+'</p><a href="'+esc(url)+'" target="_blank" rel="noopener noreferrer" class="inline-block mt-5 bg-blue-600 hover:bg-blue-500 px-4 py-2 rounded-lg text-sm font-semibold">'+label+' ↗</a></div>'}
function section(k){var m=selected;if(!m)return;var b=document.getElementById('section-body'),t=document.getElementById('section-title'),u=document.getElementById('section-subtitle'),name={manuali:'Manuali',errori:'Codici errore',ricambi:'Ricambi',schemi:'Schemi',service:'Parametri',dati:'Dati tecnici'}[k];document.getElementById('view-functions').classList.add('hidden');document.getElementById('view-content').classList.remove('hidden');t.textContent='Daikin — '+m.name+' — '+name;u.textContent=m.code+' · '+m.type;if(k==='manuali'){b.innerHTML='<div class="space-y-3">'+m.docs.map(function(x){return '<a href="'+esc(x[1])+'" target="_blank" rel="noopener noreferrer" class="block bg-blue-600 p-4 rounded-xl font-semibold">'+esc(x[0])+' <span class="float-right">↗</span></a>'}).join('')+'</div>';return}if(k==='errori'){b.innerHTML='<div class="bg-amber-500/10 border border-amber-500/30 p-4 rounded-xl text-xs text-amber-100 mb-4">Prima di intervenire togli alimentazione. Le procedure sono controlli iniziali: fa sempre fede il manuale della variante installata.</div><div class="space-y-3">'+codes.map(function(c){return '<article class="bg-slate-800 border border-slate-700 p-4 rounded-xl"><b class="text-red-300">'+c[0]+'</b><h3 class="font-semibold mt-2">'+c[1]+'</h3><p class="text-sm text-slate-400 mt-2">'+c[2]+'</p></article>'}).join('')+'</div>';return}if(k==='ricambi'){b.innerHTML=box('Ricambi del modello','Per il ricambio corretto sono necessari codice modello completo e matricola: distinta ed esploso dipendono dalla variante.','fa-gears','Supporto e documentazione',parts);return}if(k==='schemi'){b.innerHTML=box('Schemi del modello','Gli schemi elettrici e frigoriferi sono nel manuale installazione/service della variante esatta.','fa-diagram-project','Apri manuale',m.docs[0][1]);return}if(k==='service'){b.innerHTML=box('Parametri service','I parametri dipendono da serie, scheda e mercato. Non sono riportati valori generici per evitare configurazioni errate.','fa-sliders','Procedura ufficiale',m.docs[0][1]);return}b.innerHTML=box('Dati tecnici','Serie: '+esc(m.name)+' · codice: '+esc(m.code)+' · tipo: '+esc(m.type)+'. Per potenza, refrigerante, limiti e collegamenti consulta la variante esatta.','fa-circle-info','Catalogo dati ufficiale',support)}
window.selectBrand=function(b){if(b!=='Daikin'){document.getElementById('view-home').classList.add('hidden');document.getElementById('view-functions').classList.remove('hidden');return}document.getElementById('view-home').classList.add('hidden');document.getElementById('view-functions').classList.remove('hidden');categories()};
window.daikinCategories=categories;window.daikinModels=models;window.daikinDetail=detail;window.daikinSection=section;
window.openBrandMenu=function(){document.getElementById('view-content').classList.add('hidden');document.getElementById('view-functions').classList.remove('hidden');categories()};
})();
